(add-hook 'text-mode-hook (lambda ()         
                            (display-line-numbers-mode 1)
                            (visual-line-mode 1)
                            (display-fill-column-indicator-mode 1)
                            (electric-pair-mode 1)
                            (electric-indent-mode 1)
                            (setq-local display-fill-column-indicator-column 120)
                            (when (require 'highlight-indentation nil t)
                              (highlight-indentation-mode 1))))
